<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="robot_essentials">
	<xacro:macro name="wheel" params="prefix suffix reflect">

		<link name="${prefix}_${suffix}_wheel">
		  <visual>
		    <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
		    <geometry>
		      <cylinder radius="${wheeldiam/2}" length="0.1"/>
		    </geometry>
		    <material name="black"/>
		  </visual>
		  <collision>
		    <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
		    <geometry>
		      <cylinder radius="${wheeldiam/2}" length="0.1"/>
		    </geometry>
		  </collision>
		  <xacro:default_inertial mass="1"/>
		</link>
		<joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
		  <axis xyz="0 1 0" rpy="0 0 0" />
		  <parent link="${prefix}_base"/>
		  <child link="${prefix}_${suffix}_wheel"/>
		  <origin xyz="${baselen*reflect/3} 0 -${wheeldiam/2+.05}" rpy="0 0 0"/>
		</joint>

		<transmission name="${prefix}_${suffix}_wheel_trans">
		  <type>transmission_interface/SimpleTransmission</type>
		  <actuator name="${prefix}_${suffix}_wheel_motor">
		    <mechanicalReduction>1</mechanicalReduction>
		  </actuator>
		  <joint name="${prefix}_${suffix}_wheel_joint">
		    <hardwareInterface>VelocityJointInterface</hardwareInterface>
		  </joint>
		</transmission>
		<gazebo reference="${prefix}_${suffix}_wheel">
		  <mu1 value="200.0"/>
		  <mu2 value="100.0"/>
		  <kp value="10000000.0" />
		  <kd value="1.0" />
		  <material>Gazebo/Grey</material>
		</gazebo>

	  </xacro:macro>

	  <xacro:macro name="leg" params="prefix reflect">
		<link name="${prefix}_leg">
		  <visual>
		    <geometry>
		      <box size="${leglen} 0.1 0.2"/>
		    </geometry>
		    <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/>
		    <material name="white"/>
		  </visual>
		  <collision>
		    <geometry>
		      <box size="${leglen} 0.1 0.2"/>
		    </geometry>
		    <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/>
		  </collision>
		  <xacro:default_inertial mass="10"/>
		</link>

		<joint name="base_to_${prefix}_leg" type="fixed">
		  <parent link="base_link"/>
		  <child link="${prefix}_leg"/>
		  <origin xyz="0 ${reflect*(width+.02)} 0.25" />
		</joint>

		<link name="${prefix}_base">
		  <visual>
		    <geometry>
		      <box size="${baselen} 0.1 0.1"/>
		    </geometry>
		    <material name="white"/>
		  </visual>
		  <collision>
		    <geometry>
		      <box size="${baselen} 0.1 0.1"/>
		    </geometry>
		  </collision>
		  <xacro:default_inertial mass="10"/>
		</link>

		<joint name="${prefix}_base_joint" type="fixed">
		  <parent link="${prefix}_leg"/>
		  <child link="${prefix}_base"/>
		  <origin xyz="0 0 ${-leglen}" />
		</joint>
		
		<xacro:wheel prefix="${prefix}" suffix="front" reflect="1"/>
		<xacro:wheel prefix="${prefix}" suffix="back" reflect="-1"/>
	  </xacro:macro>
		
	<!--
	<xacro:macro name="robot_wheel" params="prefix originY">
		  <link name="${prefix}_leg">
			<visual>
			  <geometry>
				<box size="0.6 0.1 0.2"/>
			  </geometry>
			  <origin rpy="0 1.57075 0" xyz="0 0 -0.3"/>
			  <material name="white"/>
			</visual>
		  </link>

		  <joint name="base_to_${prefix}_leg" type="fixed">
			<parent link="base_link"/>
			<child link="${prefix}_leg"/>
			<origin xyz="0 ${originY} 0.25"/>
		  </joint>

		  <link name="${prefix}_base">
			<visual>
			  <geometry>
				<box size="0.4 0.1 0.1"/>
			  </geometry>
			  <material name="white"/>
			</visual>
		  </link>

		  <joint name="${prefix}_base_joint" type="fixed">
			<parent link="${prefix}_leg"/>
			<child link="${prefix}_base"/>
			<origin xyz="0 0 -0.6"/>
		  </joint>

		  <link name="${prefix}_front_wheel">
			<visual>
			  <origin rpy="1.57075 0 0" xyz="0 0 0"/>
			  <geometry>
				<cylinder length="0.1" radius="0.035"/>
			  </geometry>
			  <material name="black"/>
			  <origin rpy="0 0 0" xyz="0 0 0"/>
			</visual>
		  </link>
		  <joint name="${prefix}_front_wheel_joint" type="continuous">
			<axis rpy="0 0 0" xyz="0 1 0"/>
			<parent link="${prefix}_base"/>
			<child link="${prefix}_front_wheel"/>
			<origin rpy="0 0 0" xyz="0.133333333333 0 -0.085"/>
		  </joint>

		  <link name="${prefix}_back_wheel">
			<visual>
			  <origin rpy="1.57075 0 0" xyz="0 0 0"/>
			  <geometry>
				<cylinder length="0.1" radius="0.035"/>
			  </geometry>
			  <material name="black"/>
			</visual>
		  </link>
		  <joint name="${prefix}_back_wheel_joint" type="continuous">
			<axis rpy="0 0 0" xyz="0 1 0"/>
			<parent link="${prefix}_base"/>
			<child link="${prefix}_back_wheel"/>
			<origin rpy="0 0 0" xyz="-0.133333333333 0 -0.085"/>
		  </joint>
	</xacro:macro> -->
</robot>
